pull_request_rules:
- actions:
    merge:
      method: rebase
      rebase_fallback: null
      strict: true
  conditions:
  - label!=no-mergify
  - '#approved-reviews-by>=1'
  - status-success=continuous-integration/jenkins/pr-merge
  name: default
