- project:
    check:
      jobs:
        - fi-tox-mypy:
            vars:
              dependencies:
                - krb5-devel
        - fi-tox-lint:
            vars:
              dependencies:
                - krb5-devel
        - fi-tox-format:
            vars:
              dependencies:
                - krb5-devel
        - fi-tox-python38:
            vars:
              dependencies:
                - krb5-devel
        - fi-tox-python39:
            vars:
              dependencies:
                - krb5-devel
        - fi-tox-python310:
            vars:
              dependencies:
                - krb5-devel
                - python3.10-devel
        - fi-tox-docs:
            vars:
              dependencies:
                - krb5-devel
        - fi-tox-bandit:
            vars:
              dependencies:
                - krb5-devel
        - fi-tox-diff-cover:
            vars:
              dependencies:
                - krb5-devel
