- project:
    check:
      jobs:
        - fi-tox-mypy:
            vars:
              dependencies:
                - krb5-devel
        - fi-tox-lint:
            vars:
              dependencies:
                - krb5-devel
        - fi-tox-format:
            vars:
              dependencies:
                - krb5-devel
        - fi-tox-python310:
            vars:
              dependencies:
                - krb5-devel
                - python3.10-devel
        - fi-tox-python311:
            vars:
              dependencies:
                - krb5-devel
        - fi-tox-python312:
            vars:
              dependencies:
                - krb5-devel
                - python3.12-devel
        - fi-tox-docs:
            vars:
              dependencies:
                - krb5-devel
        - fi-tox-bandit:
            vars:
              dependencies:
                - krb5-devel
        - fi-tox-diff-cover:
            vars:
              dependencies:
                - krb5-devel
                - python3.12-devel
              tox_envlist: "py312,diff-cover"
              job_dependencies: "python312"
