- job:
    name: tox-python37
    description: |
      Run unit tests for a Python project under cPython version 3.7.

      Uses tox with the ``py37`` environment.

      Ensures that the python37 interpreter is installed.

    parent: tox
    run: ci/test-tox.yaml
    vars:
      tox_env: py37
      job_dependencies:
        - python37
        - tox
    nodeset:
      nodes:
        name: test-node
        label: cloud-fedora-35

- job:
    name: simple-tox-docs
    description: |
      Build docs in tox.

      Uses tox with the ``docs`` environment.

      Ensure all the dependencies for docs building are
      installed.

    parent: tox
    run: ci/test-tox.yaml
    vars:
      tox_env: docs
      job_dependencies:
        - tox
    nodeset:
      nodes:
        name: test-node
        label: cloud-fedora-35

- project:
    check:
      jobs:
        #- tox-mypy
        - tox-lint:
            vars:
              dependencies:
                - krb5-devel
        - tox-format:
            vars:
              dependencies:
                - krb5-devel
        - tox-python38:
            vars:
              dependencies:
                - krb5-devel
        - tox-python39:
            vars:
              dependencies:
                - krb5-devel
        - simple-tox-docs:
            vars:
              dependencies:
                - krb5-devel
        - tox-bandit:
            vars:
              dependencies:
                - krb5-devel
        - tox-diff-cover:
            vars:
              dependencies:
                - krb5-devel
