- project:
    check:
      jobs:
        - tox-mypy:
            vars:
              dependencies:
                - krb5-devel
        - tox-lint:
            vars:
              dependencies:
                - krb5-devel
        - tox-format:
            vars:
              dependencies:
                - krb5-devel
        - tox-python38:
            vars:
              dependencies:
                - krb5-devel
        - tox-python39:
            vars:
              dependencies:
                - krb5-devel
        - tox-python310:
            vars:
              dependencies:
                - krb5-devel
        - simple-tox-docs:
            vars:
              dependencies:
                - krb5-devel
        - tox-bandit:
            vars:
              dependencies:
                - krb5-devel
        - tox-diff-cover:
            vars:
              dependencies:
                - krb5-devel
