version: "3.5"

services:
  hostness:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: "hostness"
    hostname: "hostness-service"
    network_mode: host
    tty: true
    restart: unless-stopped
