# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
# If adding new functions to this file, note that you can add help text to the function
# by defining a variable with name _<function>_help containing the help text

hotstart (){
    systemctl --user start hub.service relay.service
}

hotstop (){
    systemctl --user stop hub.service relay.service
}

hotrestart (){
    systemctl --user restart hub.service relay.service
}

hotstatus (){
    systemctl --user status hub.service relay.service
}
