# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
# If adding new functions to this file, note that you can add help text to the function
# by defining a variable with name _<function>_help containing the help text

hotstart (){
    systemctl --user start hotness.service
}

hotstop (){
    systemctl --user stop hotness.service
}

hotrestart (){
    systemctl --user restart hotness.service
}

hotstatus (){
    systemctl --user status hotness.service
}

hotlog (){
    journalctl -f --user-unit hotness.service
}
