# -*- coding: utf-8 -*-
#
# This file is part of the-new-hotness project.
# Copyright (C) 2019  Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,
# USA.
"""Unit tests for `hotness.packit`"""
import logging
from hotness import packit

from hotness.tests.test_base import HotnessTestCase

config = {
    "fas_user": "zlopez",
    "pagure_user_token": "B3GAL4JY32KEHMI7AJN7D53IH7Z4T1RBPD0XZ7MNBXI1T686S1OAH1IO2Q1PZP5B",
    "dist_git_url": "https://src.stg.fedoraproject.org/",
    "changelog_template": "Update to {version}",
    "pull_request_template": "This pull request was automatically"
                             " generated by the-new-hotness for {package}"
                             " to update it to version {version}"
}


class TestPackit(HotnessTestCase):
    """
    Test class for `hotness.packit`.
    """

    def setUp(self):
        super(TestPackit, self).setUp()
        self.packit = packit.Packit(config)
        packit._log.setLevel(logging.DEBUG)

    def test_create_pull_request(self):
        """
        Assert that pull request is created for existing package.
        If this test passes than everything is done.
        """
        self.packit.create_pull_request("python-dockerpty", "0.0.24")
